### PR TITLE
AK4 Puppi V18 jets Pileup jet ID BDT training weights  

### PR DESCRIPTION
**Pull request by nurfikri89**
This PR adds Pileup jet ID BDT training weights for AK4 Puppi (V18) jets, which was produced by Jihoon Shin (@jshin96). The  DYto2L Winter24 JMENanoV14 sample was used for the training. Details of the training were presented in a JMAR [meeting](https://indico.cern.ch/event/1429230/#3-run3-pileup-jet-id-training).

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@cms-sw/reconstruction-l2 can you sign please?

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

only new data files, already tested via https://github.com/cms-sw/cmssw/pull/46137

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Pull request merged**
