### PR TITLE
renaming offline variables

### PR DESCRIPTION
**Pull request by jbrands**
This PR is to have the same variable names for online and offline pu ID.
The affected variables are: DRweighted, pull, jetPt and jetEta

### CODE REVIEW

**Comment by ghost** [comment]
@jbrands I will merge this for 76X then backport if needed.

**Comment by slava77** [comment]
@jbrands 
I see that the same file names are used as before.
Is this change transparent to the CMSSW software? if not, this will break 76X and should not be done like this: introduce files with new names, then pick them up in the code in CMSSW.

**Comment by ghost** [comment]
@jbrands @slava77 Maybe this should be merged along a corresponding cmssw PR?

**Comment by ghost** [comment]
@jbrands @slava77 I've tested locally to build RecoJets/JetProducers package while pointing the data to what was included in this PR and observed no issues compiling.
I've then tried to run some test from the package test folder, but they don't seems up to date (pointing to old RelVal files...)

**Comment by slava77** [comment]
On 10/13/15 3:17 PM, Alessandro Degano wrote:

> @jbrands https://github.com/jbrands @slava77
> https://github.com/slava77 I've tested locally to build
> RecoJets/JetProducers package while pointing the data to what was
> included in this PR and observed no issues compiling.
> I've then tried to run some test from the package test folder, but they
> don't seems up to date (pointing to old RelVal files...)

jenkins tests running in cms-sw/cmssw PR integration would be good to have,
together with comparisons done there.

For the /data, we could check the effects on reco L2 side, but some
better notification or issue tracking
process would be better to have.

**Comment by ghost** [comment]
@slava77 We can think about it. For the time being I don't see automatic testing of externals very straightforward. Meanwhile should I go on and merge this for 76X and keep an eye on it?

**Comment by slava77** [comment]
On 10/13/15 3:52 PM, Alessandro Degano wrote:

> @slava77 https://github.com/slava77 We can think about it. For the
> time being I don't see automatic testing of externals very
> straightforward. Meanwhile should I go on and merge this for 76X and
> keep an eye on it?

Please don't merge (in the cmsdist) just yet.

**Comment by slava77** [comment]
@degano 
let's move discussion to #5 . 
This one is becoming too confusing.

**Pull request merged**
