### PR TITLE
New pileup Jet Id weights for 76X

### PR DESCRIPTION
**Pull request by jbrands**
New pileup Jet Id weights trained on DY samples by @kkousour and @ahinzmann. Validation plots can be found here: http://www.hephy.at/user/jbrandstetter/PUId_validation76X/

### CODE REVIEW

**Comment by ghost** [comment]
@jbrands I will now merge this and prepare the corresponding PR for CMSDIST for the branch 8_1_X.

**Comment by ahinzmann** [comment]
@degano : Could you make a version of this for all 76X, 80X and 81X.
The reason is that this will be used for an analysis recipes in 76X and 80X as well.

**Comment by ghost** [comment]
@ahinzmann The tests are now running for 81X in cms-sw/cmsdist#2166, it can be backported when it'll be integrated.

**Comment by ahinzmann** [comment]
Thanks you!

**Comment by slava77** [comment]
We need 80X and 76X versions of this.
I mentioned 80X in the ORP yesterday, although only verbally.
@degano please clarify if you can make these.

**Comment by slava77** [comment]
well, the comment should have gone to the cmsdist PR, sorry

**Comment by ghost** [comment]
@slava77 Sure I'll make the PRs now.

**Pull request merged**
