### PR TITLE
Including weights for 94X and 102X PUjetID training

### PR DESCRIPTION
**Pull request by alefisico**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-data/RecoJets-JetProducers/pull/10	be78e2d 
- based on validation in the cmssw PR cms-sw/cmssw#28984

**Comment by silviodonato** [comment]
@mrodozov @smuzaffar @tulamor
https://github.com/cms-sw/cmssw/pull/28984 is fully signed and ready to be merged with this PR

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Pull request merged**
