### PR TITLE
new weight files

### PR DESCRIPTION
**Pull request by jbrands**
This PR is once again just a renaming. This time hopefully the last. I will do a PR for the bug fix in RecoJets I have done and for which the renaming was necessary. Again the weight files with the ending __newNames_ are the ones which are now used in my code. The other ones are the old weight files.

### CODE REVIEW

**Comment by jbrands** [comment]
This is the corresponding PR: https://github.com/cms-sw/cmssw/pull/12053

**Comment by slava77** [comment]
@degano please check and merge this
Now there is PR in CMSSW that needs this data change

**Comment by ghost** [comment]
@jbrands @slava77 I've merged it for 76X here: https://github.com/cms-sw/cmsdist/pull/1925

**Comment by slava77** [comment]
@degano 
Thank you.

**Comment by ahinzmann** [comment]
I'd like to ask to merge this in 74X and 75X as well, such that it can be used in analyses.
It it possible with this PR, or do we need to create a new one?

**Pull request merged**
