### PR TITLE
new and old BDTG weights

### PR DESCRIPTION
**Pull request by jbrands**
This PR leaves the old files with old variables names unchanged and additionally adds the new weight files. I will use the new variable names to fix the bug for the cutbased id in RecoJets/JetProducers

### CODE REVIEW

**Comment by slava77** [comment]
is the content of the files with already available names the same as before?
(it's not easy to check from the web)

**Comment by jbrands** [comment]
the files with the appendix __newNames_ are the files which where already introduced in https://github.com/cms-data/RecoJets-JetProducers/pull/4/files
So the files from the previous PR have been renamed.
The files without this appendix are the original(which got changed by the previous PR and now are changed backed) weight files. This original files are used at the moment but will be superceded by the __newNames_ files.

**Comment by slava77** [comment]
@jbrands 
thanks for the clarification

**Comment by ghost** [comment]
@slava77 I've tested this addition vs the existing CMSSW package. Can this go in now?

**Comment by slava77** [comment]
@degano 
I haven't checked the files myself.
If you can confirm that the files with the same names as currently in CMSSW data are unchanged, please go ahead and include this one in the distribution.

**Comment by ghost** [comment]
@slava77 Yes, I confirm that files with same names have same content. I'll go ahead and merge in 76X.

**Pull request merged**
